server:
  port: 28133

version: /v1 ##版本号

eureka:
  instance: ##心跳检测时长
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://10.12.70.39:8761/eureka/

logging:
  level:
    com.aspire.mirror.monitor.server: debug
  file: /opt/data/logs/monitor-schedule-service.log

validCode:
  check: false #是否校验验证码，false只校验格式

spring:
  kafka: # kafka 配置
    bootstrap-servers: 10.12.70.40:9092
    producer:
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      max-request-size: 10000000
    consumer:
      group-id: consumer_alert_service_1
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 2000
      session.timeout.ms: 20000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 3    # 配置partions分区数, 保证每个分区至少1个消费线程
    properties:
      session.timeout.ms: 60000