server:
  port: 28129

version: v1

theme_access_url: http://10.12.70.37:8129/v1/theme/createThemeData

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 ##心跳检测时长
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 8000

mirror:
  feign:
    theme:
      value: THEME-SERVICE
    template:
      value: TEMPLATE-SERVICE
    common:
      value: COMMON-SERVICE
    alert:
      value: ALERT-SERVICE


druid:
  url: jdbc:mysql://10.1.203.99:3306/cmdb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  username: root
  password: roo,q1Il.t
  useSSL: false


mybatis:
  mapperLocations:
    - classpath*:sqlmap/*Mapper.xml
  type-aliases-package:
     org.springboot.sample.entity

spring:
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0

sample:
  zipkin:
    enabled: true

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: true
  file: ./composite.log

ribbon:
  ReadTimeout: 240000
  ConnectTimeout: 120000

spring.mail.default-encoding: UTF-8
spring.mail.host: 10.12.8.191
#发送者的邮箱账号
spring.mail.username: wang@osa.com
#发送者的邮箱密码
spring.mail.password: wang
#端口
spring.mail.port: 25
#协议
spring.mail.protocol: smtp
spring.mail.properties.mail.smtp.auth: false
spring.mail.properties.mail.smtp.starttls.enable: false
spring.mail.properties.mail.smtp.starttls.required: false

sms:
  url: http://127.0.0.1:2000/test
  target: test
  password: pasw

cmdb:
  import:
    template:
      maintenance:
        project: '项目名称[必填],合同编号,合同供应商,维保类型,服务形式[必填],数量,开始时间[必填],结束时间[必填],服务供应商[必填],设备区域[必填],维保对象类型[必填],采购类型[必填],金额(万),设备类型'
        repairevent: '事件名称,级别,发生省份,发生地市,厂家,设备类型,设备型号,典配类型,维保归属,故障部件类型,故障开始时间,故障消除时间,故障处理时长,故障处理次数,备件部件更换次数'
        problemevent: '故障名称,故障等级,发生省份,发生地市,厂家,设备类型,设备型号,典配类型,维保归属,故障部件类型,故障开始时间,业务恢复时间,故障消除时间,业务恢复时长,故障处理时长,故障处理次数,备件部件更换次数,故障报告及相关证明材料'
        equipmentproblem: '问题名称,级别,发生省份,发生地市,厂家,设备类型,设备名称,典配类型, 发生时间,状态,解决时间,问题/需求,问题提出人及电话,问题报告word版'
        maintensoftware: '项目[必填],分类[必填],软件名称[必填],单位[必填],数量[必填],服务厂家[必填],联系人[必填],联系方式[必填],本期维保起始时间[必填], 本期维保结束时间[必填],维保管理员[必填],备注'
        maintenanceProjectBindDevice: '项目名称[必填],设备序列号[必填]'
#spring:
#  mail: # JavaMailSender 邮件发送的配置
#    switch: true # 发送邮件开关,默认值为true
#    host: smtp.qq.com
#    username: 3160652993@qq.com
#    password: jessica9192
#    properties:
#      mail:
#        transport:
#          protocol: smtp
#        smtp:
#          auth: true
#          starttls: # TLS协议
#            enable: true
#            required: true
order.config:
  orderBase: http://10.12.8.194:8086 #bpmurl
  trendsUrl: /runtime/bpmInstStatistics/v1/instTrend #工单趋势
  allTypeUrl: http://10.12.8.194:8087/flow/def/v1/listJson #查询所有工单类型
  distributionUrl: /runtime/bpmInstStatistics/v1/instDistribution #工单分布
  orderNumUrl: /runtime/bpmInstStatistics/v1/getAccountByParam #获取日增、周关、待办工单数
  orderStatisticsUrl: /runtime/bpmInstStatistics/v1/instStatistics #工单统计

bpm:
    token:
      url: http://10.12.8.194:8088/auth
      username: admin
      password: 123456
