server:
  port: 8128

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 ##心跳检测时长
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

druid: # 开发环境:10.12.70.38   # 本地:127.0.0.1
                 url: jdbc:mysql://10.12.70.38:3306/mirror?useUnicode=true&characterEncoding=UTF-8
                 username: root
                 password: root
                 useSSL: false
  
# 对接的cmdb标识, 如果未配置, 默认对接微服务cmdb
# cmdb: 微服务内部cmdb
# osa:  osa系统的cmdb服务  
cmdb.service: 
  identity: cmdb 
  #identity: osa 
  #url: http://172.16.108.52:8080/osa_web   

mybatis:
  mapperLocations:
    - classpath*:sqlmap/*Mapper.xml
  type-aliases-package:
     org.springboot.sample.entity

##LTS-->Client端配置
lts:
  jobclient:
    cluster-name: mirror_cluster                   # 开发环境:10.12.70.38
    registry-address: zookeeper://127.0.0.1:2181   # 61测试IP地址:10.153.1.61
    node-group: mirror_jobclient
    use-retry-client: true
    configs:
      job:
        fail:
          store: mapdb

     
spring:
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
      
  mail: # JavaMailSender 邮件发送的配置
    switch: true # 发送邮件开关,默认值为true
    host: smtp.qq.com
    username: 578825720@qq.com
    password: xxxxx
    properties:
      mail:
        transport: 
          protocol: smtp
        smtp:
          auth: true
          starttls: # TLS协议
            enable: true
            required: true
#          socketFactory: # SSL协议
#            port: 465
#            class: javax.net.ssl.SSLSocketFactory       

redisson:
  config-file:
    yaml: redisson/singleServer.yml
    
reportData:
  timeout: 300        # 报表数据抓取和处理超时时间，单位s，默认为5分钟
  checkInterval: 10   # 报表数据超时检测周期    默认为10s     

sample:
  zipkin:
    enabled: true

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: true

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 60000