server:
  port: 8761

#============== 基础数据同步相关配置  ===================
basicDataSync:
  proxyIdentity: miguHZ_room
  url: http://10.12.3.123:8761/template
  interval: 5   # 同步间隔, 单位秒

#============== indexProxy数据库配置  ===================
indexProxyDb:
#  url: jdbc:mysql://10.12.70.38:3306/index_proxy?useUnicode=true&useSSL=false&characterEncoding=UTF-8
#  username: root
#  password: mirror@123
  url: jdbc:oracle:thin:@10.1.203.50:1522:db12c
  username: bmc_dev
  password: bmc_dev_50
  driver-class-name: oracle.jdbc.driver.OracleDriver
  mapperLocations:
#    - classpath*:sqlmap/indexproxy/*Mapper.xml
    - classpath*:oraclesqlmap/indexproxy/*Mapper.xml

# 中间件启用开关
middleware.configuration.switch:
  kafka: false
  redis: false
#  tomcat: false

#============== kafka ===================
# 本地机房kafka
local:
  kafka:
    bootstrap-servers: 10.1.5.103:9092
    producer:
      retries: 0
      batch-size: 5
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: consumer_index_proxy
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 500
      session.timeout.ms: 60000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 3    # 配置partions分区数, 保证每个分区一个消费线程
    properties:
      session.timeout.ms: 60000
#     max.poll.records: 10

  roomId: 1  # 机房id

#============== 中央机房 kafka ===================
centerRoom:
  kafka:
    enable: false     # 启用开关
    bootstrap-servers: 10.12.12.245:9092
    producer:
      retries: 0
      batch-size: 5
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: consumer_index_proxy
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 3000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 3    # 配置partions分区数, 保证每个分区一个消费线程

###-----redisson配置
redisson:
  activeConfig: singleServerConfig
  singleServerConfig:
    idleConnectionTimeout: 10000
    pingTimeout: 1000
    connectTimeout: 10000
    timeout: 3000
    retryAttempts: 3
    retryInterval: 1500
    # password: foo
    subscriptionsPerConnection: 5
    clientName: null
    address: "redis://10.1.5.103:6379"
    subscriptionConnectionMinimumIdleSize: 1
    subscriptionConnectionPoolSize: 50
    connectionMinimumIdleSize: 32
    connectionPoolSize: 64
    database: 0
    dnsMonitoringInterval: 5000
  clusterServersConfig:
    idleConnectionTimeout: 10000
    pingTimeout: 1000
    connectTimeout: 10000
    timeout: 3000
    retryAttempts: 3
    retryInterval: 1500
    failedSlaveReconnectionInterval: 3000
    failedSlaveCheckInterval: 60000
    password: null
    subscriptionsPerConnection: 5
    clientName: null
    subscriptionConnectionMinimumIdleSize: 1
    subscriptionConnectionPoolSize: 50
    slaveConnectionMinimumIdleSize: 32
    slaveConnectionPoolSize: 64
    masterConnectionMinimumIdleSize: 32
    masterConnectionPoolSize: 64
    readMode: "SLAVE"
    subscriptionMode: "SLAVE"
    nodeAddresses:
    - "redis://127.0.0.1:7004"
    - "redis://127.0.0.1:7001"
    - "redis://127.0.0.1:7000"
    scanInterval: 1000
    pingConnectionInterval: 0
    keepAlive: false
    tcpNoDelay: false
  threads: 0
  nettyThreads: 0
  transportMode: "NIO"


inpsection.service.itemdata.callback: http://127.0.0.1:8128/v1/report_data/itemdata_callback
monitor.service.itemdata.callback: http://10.12.3.123:8761/alert/v1/alerts/itemMonitorEvent/callback
bizmonitor.service.itemdata.callback: http://10.12.3.123:8761/alert/v1/alerts/itemMonitorEvent/callback


logging:
  level:
    org.springframework: info
    com.aspire.mirror.indexproxy: info
  file: ./index-proxy.log