server:
  port: 8149

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 ##心跳检测时长
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

druid: # 开发环境:10.12.70.38
  url: jdbc:mysql://10.12.70.38:3306/lts?useSSL=false&useUnicode=true&characterEncoding=UTF-8
  username: root   #root
  password: root   #root
  useSSL: false

mybatis:
  mapperLocations:
    - classpath*:sqlmap/*Mapper.xml
  type-aliases-package:
     org.springboot.sample.entity

##LTS-->jobtracker端配置
lts:
  jobtracker:
    cluster-name: mirror_cluster
    listen-port: 35001
    registry-address: zookeeper://10.12.70.39:2181
    bind-ip: 10.1.28.54
    configs:
      job.logger: mysql
      job.queue: mysql   # 开发环境:10.12.70.38
      jdbc.url: jdbc:mysql://10.12.70.38:3306/lts?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      jdbc.username: root
      jdbc.password: root



     
spring:
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
      
  mail: # JavaMailSender 邮件发送的配置
    switch: true # 发送邮件开关,默认值为true
    host: smtp.qq.com
    username: 578825720@qq.com
    password: xxxxx
    properties:
      mail:
        transport: 
          protocol: smtp
        smtp:
          auth: true
          starttls: # TLS协议
            enable: true
            required: true
#          socketFactory: # SSL协议
#            port: 465
#            class: javax.net.ssl.SSLSocketFactory        

sample:
  zipkin:
    enabled: true

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: true

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 60000