server:
  port: 8761
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 ##心跳检测时长
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

druid:
#  url: jdbc:mysql://10.12.70.38:3306/mirror?useUnicode=true&characterEncoding=UTF-8
#  username: root
#  password: mirror@123
#  useSSL: false
   url: jdbc:oracle:thin:@10.1.203.50:1522:db12c
   username: bmc_dev
   password: bmc_dev_50
   driver-class-name: oracle.jdbc.driver.OracleDriver


mybatis:
  mapperLocations:
    - classpath*:oraclesqlmap/*Mapper.xml
  type-aliases-package:
     org.springboot.sample.entity

spring:
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
  kafka:
    bootstrap-servers: 10.12.70.37:9092
    producer:
      retries: 0
      batch-size: 5
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: consumer_log_theme_1
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 500
      session.timeout.ms: 60000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 3    # 配置partions分区数, 保证每个分区一个消费线程
    properties:
      session.timeout.ms: 60000
sample:
  zipkin:
    enabled: true
    
#es
elasticsearch.ip: 10.12.70.38
elasticsearch.port: 9300
elasticsearch.nodeType: client
elasticsearch.clusterName: elasticsearch
elasticsearch.indexName: mirror-theme
elasticsearch.index.fields.limit: 10000

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: true
    com.dy.springboot.server.mapper: DEBUG
    com.aspire.mirror.theme.server.dao: DEBUG
  file: ./logs/theme.log

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 60000

###-----redisson配置
redisson:
  activeConfig: singleServerConfig
  singleServerConfig:
    idleConnectionTimeout: 10000
    pingTimeout: 1000
    connectTimeout: 10000
    timeout: 3000
    retryAttempts: 3
    retryInterval: 1500
    password: foo
    subscriptionsPerConnection: 5
    clientName: null
    address: "redis://10.12.70.38:6379"
    subscriptionConnectionMinimumIdleSize: 1
    subscriptionConnectionPoolSize: 50
    connectionMinimumIdleSize: 32
    connectionPoolSize: 64
    database: 0
    dnsMonitoringInterval: 5000
  clusterServersConfig:
    idleConnectionTimeout: 10000
    pingTimeout: 1000
    connectTimeout: 10000
    timeout: 3000
    retryAttempts: 3
    retryInterval: 1500
    failedSlaveReconnectionInterval: 3000
    failedSlaveCheckInterval: 60000
    password: null
    subscriptionsPerConnection: 5
    clientName: null
    subscriptionConnectionMinimumIdleSize: 1
    subscriptionConnectionPoolSize: 50
    slaveConnectionMinimumIdleSize: 32
    slaveConnectionPoolSize: 64
    masterConnectionMinimumIdleSize: 32
    masterConnectionPoolSize: 64
    readMode: "SLAVE"
    subscriptionMode: "SLAVE"
    nodeAddresses:
    - "redis://127.0.0.1:7004"
    - "redis://127.0.0.1:7001"
    - "redis://127.0.0.1:7000"
    scanInterval: 1000
    pingConnectionInterval: 0
    keepAlive: false
    tcpNoDelay: false
  threads: 0
  nettyThreads: 0
  transportMode: "NIO"

genIpBizCorrespond:
  cron: 0 0/2 *  * * ?
genThemeCache:
  cron: 0 0/5 *  * * ?