server:
  port: 28133

version: /v1 ##版本号

spring:
eureka:
  instance: ##心跳检测时长
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://10.12.70.39:8761/eureka/

logging:
  level:
    com.aspire.mirror.third.server: debug
  file: /opt/data/logs/third-service.log

validCode:
  check: false #是否校验验证码，false只校验格式