server:
  port: 8130
version: /v1
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 ##心跳检测时长
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://10.252.24.150:8761/eureka/

middleware.configuration.switch: 
  kafka: true
  redis: true
      
kafka:
  topic:
    topic_system_alerts: TOPIC_SYSTEM_ALERTS      # 系统告警kafka主题
    topic_zabbix_delete: TOPIC_ZABBIX_DELETE
    topic_zabbix_item: TOPIC_ZABBIX_ITEM
    topic_zabbix_trigger: TOPIC_ZABBIX_TRIGGER
    topic_zabbix_trends: TOPIC_ZABBIX_TRENDS

druid:
  url: jdbc:mysql://10.252.24.151:3306/test_mirror?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: Ums$yjd2@19
  useSSL: false

mybatis:
  mapperLocations:
    - classpath*:sqlmap/*Mapper.xml
  type-aliases-package:
     org.springboot.sample.entity
     
# 告警事件监听
alert.event.listener:
  AlertEventNotifier:   # 监听实现名
    switch: true        # 监听开关
    awareLevel: 4       # 告警级别:  1-提示 2-低 3-中 4-高 5-严重
    kafkaServers: vmhadoop12:9092,vmhadoop13:9092,vmhadoop14:9092
    kafkaTopic: ZW-Monitor

spring:
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
  
  kafka: # kafka 配置
    bootstrap-servers: 10.12.70.40:9092
    producer: 
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer: 
      group-id: consumer_alert_service
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 2000
      session.timeout.ms: 20000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  
    listener:
      concurrency: 3    # 配置partions分区数, 保证每个分区至少1个消费线程     
    properties: 
      session.timeout.ms: 60000          
  jackson:
    time-zone: GMT+8

  mail: # JavaMailSender 邮件发送的配置
    switch: true # 是否发送邮件,默认值为fasle
    host: szmail.aspire-tech.com
    port: 25
    username: pengguihua@aspirecn.com
    password: 'peng!234'
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: false
          starttls: # TLS协议
            enable: false
            required: false
  #          port: 465
  #          socketFactory: # SSL协议
  #            class: javax.net.ssl.SSLSocketFactory
  redis:
    #expiration: 3600 #设置缓存到期时间,单位秒
    usable: false #是否使用缓存
    redisKeyPrefixPermission: rbac-service-permission #用户权限缓存KEY前缀
    redisKeyPrefixResourceSchemaHash: rbac-service-resource-schema-hash #资源模式Hash缓存KEY前缀
    redisKeyPrefixResourceSchemaList: rbac-service-resource-schema-list #资源模式List缓存KEY前缀
    redisKeySplit: "~" #缓存KEY分割标识
    password:
    database: 2
    timeout: 5000 #客户端超时时间：单位是毫秒
    pool:
      max-active: 8 #最大连接数：能够同时建立的“最大链接个数”
      max-idle: 8 #最大空闲数：空闲链接数大于maxIdle时，将进行回收
      min-idle: 0 #最小空闲数
      max-wait: -1 #最大等待时间：单位ms
    #单节点方式
    host: 10.1.5.103
    port: 6379
    #集群方式
#    cluster:
#      max-redirects: 3
#      nodes:
#      - 172.30.150.26:6381
#      - 172.30.150.32:7381
#      - 172.30.150.35:7381

sample:
  zipkin:
    enabled: true

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: info
    com.aspire.mirror.alert: info
    org.springframework.data: debug
  file: /opt/data/logs/alert-service.log

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 60000
  
#FLOW_KEY: gzsjclgd0523
#FULLNAME: admin
#ORDER_AUTOGEN_LEVEL: 4,5
#
#WSDL_URL: http://10.1.4.245:58080/bpmx/service/ProcessService?wsdl

orderAutoGen.cron: 0 0/5 *  * * ?
bpm:
  closing:
    cron: 0 0 1 * * ?
    isOpen: false
    url: http://10.1.203.87:8086/runtime/sysThirdPartyInterfaces/v1/alertOrderIsEnd
  runtime:
    url: http://10.12.8.194:8086
  token: Basic YWRtaW46NEFmeTJzNENiKzhCN2RFWFpIc08vdz09
  alert:
     Url: http://10.12.8.194:8086/bpmx/service/ProcessService?wsdl
     gjFlowkey: gjcllc
     gzFlowkey: gzcllc
     wbFlowkey: wbgllc
     acount: admin
     method: start
     namepace: http://impl.webservice.platform.hotent.com/
     gjModel: <data>{"gjyw":{"title":"@{device_ip}@{device_type}产生告警","objectType":"@{device_type}","sourceIP":"@{device_ip}","zyc":"@{idc_type}","alarmId":"@{alert_id}","objectName":"@{moni_object}","detail":"@{@{moni_index}","starttime":"@{alert_start_time}","alert_level":"@{alert_level}","objectId":"@{event_id}","POD":"@{pod_name}","ywxt":"@{biz_sys}"}}</data>
     gzModel: <data>{"gzywdxV4":{"gzbt":"@{device_ip}@{device_type}发生故障","zyc":"@{idc_type}","gzfssj":"@{alert_start_time}","ywxt":"@{biz_sys}","gzdygjgd":"@{order_id}","xdrzdgzclr":"@{user_name}","clrID":"@{user}","device_id":"@{device_id}","object_type":"@{object_type}"}}</data>
     wbModel: <data>{"wbglb":{"sqbt":"@{device_ip}@{device_type}维保申请","zyc":"@{idc_type}","gdly":"umspaidan","errororder":"@{order_id}"}}</data>

recipient:
  client:
    url: http://127.0.0.1:8088/v1/alerts/recipient/task

bdc_notify_url: http://10.1.121.65:8888/bmserver/api/alert/v1.0/notify.ajax


sms:
  url: http://127.0.0.1:2000/test
  target: test
  password: pasw

systemType: simple

sls:
  cron: 0 */1 * * * ?
  ftp:
    download:
      host: 10.12.70.40
      port: 21
      user: ftpadmin
      password: 11qq!!QQ
      mode: pasv
      path: /scan_report/pkg_app_report
    upload:
      host: 10.12.70.40
      port: 21
      user: ftpadmin
      password: 11qq!!QQ
      path: /scan_report_upload/pkg_app_report
    clear:
      days: -1
  local:
    store: /opt/temp/scan_report
    download: /scan_report_upload/pkg_app_report
  bpm:
    token:
      url: http://10.12.8.194:8088/auth
      username: admin
      password: 123456
    upload:
      url: http://10.12.8.194:8084/system/file/v1/upload
    webservice:
      url: http://10.12.8.194:8086/bpmx/service/ProcessService?wsdl
      flowkey: ldsmgd
      account: admin
      namespace: http://impl.webservice.platform.hotent.com/
      method: start
    rest:
      url: http://10.12.8.194:8086/runtime/bpmProcess/v1/loadBpmProcess

extranet_addr: http://10.5.2.101:28199

ftp:
  host: 10.12.70.40
  port: 21
  username: ftpadmin
  password: 11qq!!QQ
  path: /file_download/
  bufferSize: 8096

cmdb:
  token: 5245ed1b-6345-11e   #cmdb查询接口token

alert:
  check:
    level: 2,3,4,5  #告警级别只能是数据，以逗号分隔
  branch:    # it_yun表示中移版本
  order:
    overtime:
      todo: {"3":60,"4":30,"5":10}
      todoRemind: {"3":15,"4":10,"5":5}
      doing: {"3":720,"4":360,"5":240}
      doingRemind: {"3":480,"4":240,"5":180}
      filterTrans: {"device_type_name":"device_type","device_class_name":"device_class","room_name":"source_room","device_name":"host_name","idcType_name":"idc_type","bizSystem_name":"biz_sys","device":"device_id"}

auth:
  data:
    flag: true