FROM zixia/wechaty

ADD .npmrc /root/
ADD src /bot/src
ADD package-zixia-wechaty.json /bot/package.json

RUN set -eux;\
    npm i 

VOLUME [ \
    "/bot/.wechaty" \
    "/bot/logs" \
    "/bot/config" \
    ]

CMD ["src/index.js"]