server:
  port: 28133
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 ##心跳检测时长
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://10.12.70.39:8761/eureka/
      
      
logging:
  level:
    org.springframework: info
    com.aspire.mirror.thirdparty.alertnotify: info
    
  file: ./thirdparty-alert-notify.log    