server:
  port: 28137
version: /v1
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 ##心跳检测时长
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://10.5.2.227:8761/eureka/

kafka.topic.topic_system_alerts: TOPIC_SYSTEM_ALERTS

druid:
  url: jdbc:mysql://10.12.70.40:3306/mirror?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: 1234@qwer
  useSSL: false

mybatis:
  mapperLocations:
    - classpath*:sqlmap/*Mapper.xml
  type-aliases-package:
     org.springboot.sample.entity

spring:
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
      
  kafka: # kafka 配置
      bootstrap-servers: 10.12.70.40:9092
      producer: 
        retries: 1
        batch-size: 16384
        buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer: 
        group-id: consumer_alert_service
        auto-offset-reset: latest
        enable-auto-commit: true
        auto-commit-interval: 2000
        session.timeout.ms: 20000
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  
      listener:
        concurrency: 3    # 配置partions分区数, 保证每个分区至少1个消费线程     
      properties: 
        session.timeout.ms: 60000


sample:
  zipkin:
    enabled: true

logging:
  level:
    org.springframework: info
    #org.apache.kafka: debug
    com.aspire.mirror.alert.server: debug
  file: /opt/data/logs/alert-service.log
  
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 60000
  
elasticsearch:
  cluster-name: elasticsearch
  cluster-nodes: 10.12.70.40:9300
  sniff: false

# 告警事件监听
alert.event.listener:
  AlertEventNotifier:   # 监听实现名
    switch: false        # 监听开关
    awareLevel: 4       # 告警级别:  1-提示 2-低 3-中 4-高 5-严重
    kafkaServers: vmhadoop12:9092,vmhadoop13:9092,vmhadoop14:9092
    kafkaTopic: ZW-Monitor 
  
FLOW_KEY: epc_alarm_order
FULLNAME: admin
ORDER_AUTOGEN_LEVEL: 4,5


orderAutoGen.cron: 0 0/5 *  * * ?

WSDL_URL: http://10.12.8.192:8081/bpmx/service/ProcessService?wsdl



threadPool.size: 2
snmp4j.listenAddress: udp:127.0.0.1/8163

bpm:
  closing:
    fixedDelay: 300000
    isOpen: true
  runtime:
    url: http://10.12.8.194:8086
  token: Basic YWRtaW46NEFmeTJzNENiKzhCN2RFWFpIc08vdz09
  alert:
    Url: http://10.12.8.194:8086/bpmx/service/ProcessService?wsdl
    tuningFlowkey: gjdygd
    gjFlowkey: gjcllc
    gzFlowkey: gzcllc
    wbFlowkey: wbgllc
    acount: admin
    method: start
    namepace: http://impl.webservice.platform.hotent.com/
    gjModel: <data>{"gjyw":{"title":"@{device_ip}@{device_type}产生告警","objectType":"@{device_type}","sourceIP":"@{device_ip}","zyc":"@{idc_type}","alarmId":"@{alert_id}","objectName":"@{moni_object}","detail":"@{@{moni_index}","starttime":"@{alert_start_time}","alert_level":"@{alert_level}","objectId":"@{event_id}","POD":"@{pod_name}","ywxt":"@{biz_sys}"}}</data>
    gzModel: <data>{"gzywdxV4":{"gzbt":"@{device_ip}@{device_type}发生故障","zyc":"@{idc_type}","gzfssj":"@{alert_start_time}","ywxt":"@{biz_sys}","gzdygjgd":"@{order_id}","xdrzdgzclr":"@{user_name}","clrID":"@{user}","device_id":"@{device_id}","object_type":"@{object_type}"}}</data>
    wbModel: <data>{"wbglb":{"sqbt":"@{device_ip}@{device_type}维保申请","zyc":"@{idc_type}","gdly":"umspaidan","errororder":"@{order_id}"}}</data>

recipient:
   client:
      url: http://10.12.70.39:8188/v1/alerts/recipient/task

sls:
  cron: 0 */1 * * * ?
  ftp:
    download:
      host: 10.12.70.40
      port: 21
      user: ftpadmin
      password: 11qq!!QQ
      mode: pasv
      path: /scan_report/pkg_app_report
    upload:
      host: 10.12.70.40
      port: 21
      user: ftpadmin
      password: 11qq!!QQ
      path: /scan_report_upload/pkg_app_report
    clear:
      days: -1
  local:
    store: /opt/temp/scan_report
    download: /scan_report_upload/pkg_app_report
  bpm:
    token:
      url: http://10.12.8.194:8088/auth
      username: QjguF75dA4hchFVKf7k5cg== #admin
      password: yy/Vh60lXQJSOcm+CikQow== #Asp+8888
    upload:
      url: http://10.12.8.194:8084/system/file/v1/upload
    webservice:
      url: http://10.12.8.194:8086/bpmx/service/ProcessService?wsdl
      flowkey: ldsmgd
      account: admin
      namespace: http://impl.webservice.platform.hotent.com/
      method: start
    rest:
      url: http://10.12.8.194:8086/runtime/bpmProcess/v1/loadBpmProcess
      
spring.mail.default-encoding: UTF-8
spring.mail.host: 10.12.8.191
#发送者的邮箱账号
spring.mail.username: wang@osa.com
#发送者的邮箱密码
spring.mail.password: wang
#端口
spring.mail.port: 25
#协议
spring.mail.protocol: smtp
spring.mail.properties.mail.smtp.auth: false
spring.mail.properties.mail.smtp.starttls.enable: false
spring.mail.properties.mail.smtp.starttls.required: false

sms:
  url: http://10.12.70.39:7789/?wsdl
  target: aspire
  password: aspire

ftp:
  host: 10.12.70.40
  port: 21
  username: ftpadmin
  password: 11qq!!QQ
  path: /file_download/
  bufferSize: 8096

  
AlertKpiListToKafkaTask.flag: normal
AlertKpiListToKafkaTask.intervalMinute: 5
AlertKpiListToKafkaTask.cron: 0 */5 * * * ?