server:
  port: 26379

version: /v1 ##版本号

spring:
  redis:
    cluster:
      nodes: 10.2.2.18:7001,10.2.2.19:7001,10.2.2.20:7001
      max-redirects: 3
    password: Asp@aspire+888
    database: 0
    pool:
      max-active: 8  #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1   #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8    #连接池中的最大空闲连接
      min-idle: 0    #连接池中的最小空闲连接
    timeout: 30000   #连接超时时间（毫秒）

eureka:
  instance: ##心跳检测时长
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://10.12.70.39:8761/eureka/

logging:
  level:
    # org.elasticsearch: error
    com.aspire.mirror.redis.server: debug
  file: /opt/data/logs/redis-service.log