
package com.aspire.mirror.alert.server.clientservice.process;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProcessService", targetNamespace = "http://impl.webservice.platform.hotent.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getXml", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetXml")
    @ResponseWrapper(localName = "getXmlResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetXmlResponse")
    public String getXml();

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBpmDefinition", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetBpmDefinition")
    @ResponseWrapper(localName = "getBpmDefinitionResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetBpmDefinitionResponse")
    public String getBpmDefinition(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml);

    /**
     *
     * @param taskId
     * @param destNodeId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDestNodeHandleUsers", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetDestNodeHandleUsers")
    @ResponseWrapper(localName = "getDestNodeHandleUsersResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetDestNodeHandleUsersResponse")
    public String getDestNodeHandleUsers(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId,
            @WebParam(name = "destNodeId", targetNamespace = "")
                    String destNodeId);

    /**
     *
     * @param json
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveNode", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.SaveNode")
    @ResponseWrapper(localName = "saveNodeResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.SaveNodeResponse")
    public String saveNode(
            @WebParam(name = "json", targetNamespace = "")
                    String json);

    /**
     *
     * @param json
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAlreadyMattersList", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetAlreadyMattersList")
    @ResponseWrapper(localName = "getAlreadyMattersListResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetAlreadyMattersListResponse")
    public String getAlreadyMattersList(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "json", targetNamespace = "")
                    String json);

    /**
     *
     * @param json
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProCopyList", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetProCopyList")
    @ResponseWrapper(localName = "getProCopyListResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetProCopyListResponse")
    public String getProCopyList(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "json", targetNamespace = "")
                    String json);

    /**
     *
     * @param actInstId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessOpinionByActInstId", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetProcessOpinionByActInstId")
    @ResponseWrapper(localName = "getProcessOpinionByActInstIdResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetProcessOpinionByActInstIdResponse")
    public String getProcessOpinionByActInstId(
            @WebParam(name = "actInstId", targetNamespace = "")
                    String actInstId);

    /**
     *
     * @param taskId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTaskOutNodes", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetTaskOutNodes")
    @ResponseWrapper(localName = "getTaskOutNodesResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetTaskOutNodesResponse")
    public String getTaskOutNodes(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param json
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "taskEndProcess", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.TaskEndProcess")
    @ResponseWrapper(localName = "taskEndProcessResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.TaskEndProcessResponse")
    public String taskEndProcess(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "json", targetNamespace = "")
                    String json);

    /**
     *
     * @param json
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assignUsers", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.AssignUsers")
    @ResponseWrapper(localName = "assignUsersResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.AssignUsersResponse")
    public String assignUsers(
            @WebParam(name = "json", targetNamespace = "")
                    String json);

    /**
     *
     * @param taskId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTaskNameByTaskId", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetTaskNameByTaskId")
    @ResponseWrapper(localName = "getTaskNameByTaskIdResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetTaskNameByTaskIdResponse")
    public String getTaskNameByTaskId(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param runId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTasksByRunId", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetTasksByRunId")
    @ResponseWrapper(localName = "getTasksByRunIdResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetTasksByRunIdResponse")
    public String getTasksByRunId(
            @WebParam(name = "runId", targetNamespace = "")
                    String runId);

    /**
     *
     * @param taskId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVariablesByTaskId", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetVariablesByTaskId")
    @ResponseWrapper(localName = "getVariablesByTaskIdResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetVariablesByTaskIdResponse")
    public String getVariablesByTaskId(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param taskId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTaskByTaskId", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetTaskByTaskId")
    @ResponseWrapper(localName = "getTaskByTaskIdResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetTaskByTaskIdResponse")
    public String getTaskByTaskId(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param actInstId
     * @param nodeKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFinishTaskDetailUrl", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetFinishTaskDetailUrl")
    @ResponseWrapper(localName = "getFinishTaskDetailUrlResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetFinishTaskDetailUrlResponse")
    public String getFinishTaskDetailUrl(
            @WebParam(name = "actInstId", targetNamespace = "")
                    String actInstId,
            @WebParam(name = "nodeKey", targetNamespace = "")
                    String nodeKey);

    /**
     *
     * @param taskId
     * @param signUserIds
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addSignUsers", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.AddSignUsers")
    @ResponseWrapper(localName = "addSignUsersResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.AddSignUsersResponse")
    public String addSignUsers(
            @WebParam(name = "signUserIds", targetNamespace = "")
                    String signUserIds,
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTasksByAccount", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetTasksByAccount")
    @ResponseWrapper(localName = "getTasksByAccountResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetTasksByAccountResponse")
    public String getTasksByAccount(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml);

    /**
     *
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyProcessRunByXml", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetMyProcessRunByXml")
    @ResponseWrapper(localName = "getMyProcessRunByXmlResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetMyProcessRunByXmlResponse")
    public String getMyProcessRunByXml(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml);

    /**
     *
     * @param json
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompletedMattersList", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetCompletedMattersList")
    @ResponseWrapper(localName = "getCompletedMattersListResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetCompletedMattersListResponse")
    public String getCompletedMattersList(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "json", targetNamespace = "")
                    String json);

    /**
     *
     * @param taskId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTaskFormUrl", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetTaskFormUrl")
    @ResponseWrapper(localName = "getTaskFormUrlResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetTaskFormUrlResponse")
    public String getTaskFormUrl(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param runId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVariablesByRunId", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetVariablesByRunId")
    @ResponseWrapper(localName = "getVariablesByRunIdResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetVariablesByRunIdResponse")
    public String getVariablesByRunId(
            @WebParam(name = "runId", targetNamespace = "")
                    String runId);

    /**
     *
     * @param json
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "defRecover", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.DefRecover")
    @ResponseWrapper(localName = "defRecoverResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.DefRecoverResponse")
    public String defRecover(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "json", targetNamespace = "")
                    String json);

    /**
     *
     * @param taskId
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isAllowAddSign", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.IsAllowAddSign")
    @ResponseWrapper(localName = "isAllowAddSignResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.IsAllowAddSignResponse")
    public String isAllowAddSign(
            @WebParam(name = "account", targetNamespace = "")
                    String account,
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setTaskVars", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.SetTaskVars")
    @ResponseWrapper(localName = "setTaskVarsResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.SetTaskVarsResponse")
    public String setTaskVars(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml);

    /**
     *
     * @param taskId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isSelectPath", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.IsSelectPath")
    @ResponseWrapper(localName = "isSelectPathResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.IsSelectPathResponse")
    public String isSelectPath(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param json
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "taskAssign", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.TaskAssign")
    @ResponseWrapper(localName = "taskAssignResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.TaskAssignResponse")
    public String taskAssign(
            @WebParam(name = "json", targetNamespace = "")
                    String json);

    /**
     *
     * @param defId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBpmDefinitionByDefId", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetBpmDefinitionByDefId")
    @ResponseWrapper(localName = "getBpmDefinitionByDefIdResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetBpmDefinitionByDefIdResponse")
    public String getBpmDefinitionByDefId(
            @WebParam(name = "defId", targetNamespace = "")
                    String defId);

    /**
     *
     * @param json
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProTransMattersList", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetProTransMattersList")
    @ResponseWrapper(localName = "getProTransMattersListResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetProTransMattersListResponse")
    public String getProTransMattersList(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "json", targetNamespace = "")
                    String json);

    /**
     *
     * @param taskId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApprovalItems", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetApprovalItems")
    @ResponseWrapper(localName = "getApprovalItemsResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetApprovalItemsResponse")
    public String getApprovalItems(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param json
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccordingMattersList", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetAccordingMattersList")
    @ResponseWrapper(localName = "getAccordingMattersListResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetAccordingMattersListResponse")
    public String getAccordingMattersList(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "json", targetNamespace = "")
                    String json);

    /**
     *
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFinishTask", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetFinishTask")
    @ResponseWrapper(localName = "getFinishTaskResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetFinishTaskResponse")
    public String getFinishTask(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml);

    /**
     *
     * @param taskId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTaskNode", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetTaskNode")
    @ResponseWrapper(localName = "getTaskNodeResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetTaskNodeResponse")
    public String getTaskNode(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param defId
     * @param json
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setDefOtherParam", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.SetDefOtherParam")
    @ResponseWrapper(localName = "setDefOtherParamResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.SetDefOtherParamResponse")
    public String setDefOtherParam(
            @WebParam(name = "defId", targetNamespace = "")
                    String defId,
            @WebParam(name = "json", targetNamespace = "")
                    String json);

    /**
     *
     * @param taskId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isAllowBack", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.IsAllowBack")
    @ResponseWrapper(localName = "isAllowBackResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.IsAllowBackResponse")
    public String isAllowBack(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param nodeId
     * @param runId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatusByRunidNodeId", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetStatusByRunidNodeId")
    @ResponseWrapper(localName = "getStatusByRunidNodeIdResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetStatusByRunidNodeIdResponse")
    public String getStatusByRunidNodeId(
            @WebParam(name = "runId", targetNamespace = "")
                    String runId,
            @WebParam(name = "nodeId", targetNamespace = "")
                    String nodeId);

    /**
     *
     * @param taskId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "endProcessByTaskId", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.EndProcessByTaskId")
    @ResponseWrapper(localName = "endProcessByTaskIdResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.EndProcessByTaskIdResponse")
    public String endProcessByTaskId(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessRun", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetProcessRun")
    @ResponseWrapper(localName = "getProcessRunResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetProcessRunResponse")
    public String getProcessRun(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml);

    /**
     *
     * @param defId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBpmAllNode", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetBpmAllNode")
    @ResponseWrapper(localName = "getBpmAllNodeResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetBpmAllNodeResponse")
    public String getBpmAllNode(
            @WebParam(name = "defId", targetNamespace = "")
                    String defId);

    /**
     *
     * @param runId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessRunByRunId", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetProcessRunByRunId")
    @ResponseWrapper(localName = "getProcessRunByRunIdResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetProcessRunByRunIdResponse")
    public String getProcessRunByRunId(
            @WebParam(name = "runId", targetNamespace = "")
                    String runId);

    /**
     *
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doNext", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.DoNext")
    @ResponseWrapper(localName = "doNextResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.DoNextResponse")
    public String doNext(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml);

    /**
     *
     * @param taskId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFreeJump", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetFreeJump")
    @ResponseWrapper(localName = "getFreeJumpResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetFreeJumpResponse")
    public String getFreeJump(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param json
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "taskCountersign", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.TaskCountersign")
    @ResponseWrapper(localName = "taskCountersignResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.TaskCountersignResponse")
    public String taskCountersign(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "json", targetNamespace = "")
                    String json);

    /**
     *
     * @param businessKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getByBusinessKey", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetByBusinessKey")
    @ResponseWrapper(localName = "getByBusinessKeyResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetByBusinessKeyResponse")
    public String getByBusinessKey(
            @WebParam(name = "businessKey", targetNamespace = "")
                    String businessKey);

    /**
     *
     * @param json
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPendingMattersList", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetPendingMattersList")
    @ResponseWrapper(localName = "getPendingMattersListResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetPendingMattersListResponse")
    public String getPendingMattersList(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "json", targetNamespace = "")
                    String json);

    /**
     *
     * @param defKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNodesByDefKey", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetNodesByDefKey")
    @ResponseWrapper(localName = "getNodesByDefKeyResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetNodesByDefKeyResponse")
    public String getNodesByDefKey(
            @WebParam(name = "defKey", targetNamespace = "")
                    String defKey);

    /**
     *
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "start", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.Start")
    @ResponseWrapper(localName = "startResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.StartResponse")
    public String start(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml);

    /**
     *
     * @param taskId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessRunByTaskId", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetProcessRunByTaskId")
    @ResponseWrapper(localName = "getProcessRunByTaskIdResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetProcessRunByTaskIdResponse")
    public String getProcessRunByTaskId(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param json
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setAgent", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.SetAgent")
    @ResponseWrapper(localName = "setAgentResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.SetAgentResponse")
    public String setAgent(
            @WebParam(name = "json", targetNamespace = "")
                    String json);

    /**
     *
     * @param taskId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "canSelectedUser", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.CanSelectedUser")
    @ResponseWrapper(localName = "canSelectedUserResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.CanSelectedUserResponse")
    public String canSelectedUser(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId);

    /**
     *
     * @param taskId
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNextFlowNodes", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetNextFlowNodes")
    @ResponseWrapper(localName = "getNextFlowNodesResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetNextFlowNodesResponse")
    public String getNextFlowNodes(
            @WebParam(name = "taskId", targetNamespace = "")
                    String taskId,
            @WebParam(name = "account", targetNamespace = "")
                    String account);

    /**
     *
     * @param runId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessOpinionByRunId", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetProcessOpinionByRunId")
    @ResponseWrapper(localName = "getProcessOpinionByRunIdResponse", targetNamespace = "http://impl.webservice.platform.hotent.com/", className = "com.aspire.mirror.alert.server.clientservice.process.GetProcessOpinionByRunIdResponse")
    public String getProcessOpinionByRunId(
            @WebParam(name = "runId", targetNamespace = "")
                    String runId);

}
