spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.12.70.61:3306/mirror?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      stat-view-servlet.enabled: true
      view-servlet.login-username: admin
      view-servlet.login-password: admin
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  messages:
    encoding: UTF-8


eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://10.12.70.60:8761/eureka/


mybatis:
  mapper-locations: classpath:mapper/*.xml

banner:
  charset: utf-8
  
orderAutoGen.cron: 0/30 * *  * * ?

province.name: xinjiang

province.ip.port: udp:10.242.92.90/5201


mydata.factorName: 卓望
mydata.provinceName: 内蒙古
mydata.cityName: 呼和浩特

server:
  port: 4567
  context-path: /misc
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    root: info
  file: /opt/aspire/product/ums/data/logs/misc.log

